apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  description: Python service for the ${{ values.environment }} environment
  annotations:
    example.com/environment: ${{ values.environment }}
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
