apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  title: ${{ values.app_name }}
  description: Python app for the ${{ values.app_env }} environment
  labels:
    environment: ${{ values.app_env }}
  annotations:
    github.com/project-slug: ehazan/${{ values.app_name }}

spec:
  type: service
  owner: user:default/ehazan
  lifecycle: experimental
